/**
 * Seeder: mst_product data
 */

exports.seed = async function(knex) {
  // Delete all existing entries using TRUNCATE CASCADE to handle foreign keys
  await knex.raw('TRUNCATE TABLE mst_product CASCADE');
  
  // Insert seed data
  await knex('mst_product').insert([
    {
      product_id: '0986b898-193c-4b34-af11-55f161a67993',
      type_product_id: '082b1a70-995d-4dc7-8092-3b3c2f496675',
      product_name_id: 'MS500S',
      product_name_en: 'MS500S',
      product_name_cn: 'MS500S',
      banner_product: 'product/1750524071_MS500S-LORRY.jpg',
      tagline_banner_product_id: 'Command the Road',
      tagline_banner_product_en: 'Command the Road',
      tagline_banner_product_cn: 'Command the Road',
      image_product: 'product/1750607326_MS500S-LORRY-PNG.png',
      product_description_id: 'Engineered for the toughest challenges, the MS500S Lorry Truck delivers relentless performance, exceptional durability, and unstoppable torque. Powered by a 400HP Euro V Weichai engine with 1,800Nm of torque, this truck is built to conquer steep inclines and long hauls with ease. With a FAST 10-speed transmission, high-capacity aluminum fuel tank, rugged suspension system, and intelligent braking technology, it bridges power with smart engineering. The MS500S isn\'t just a truck; it\'s the driving force behind your business.',
      product_description_en: 'Engineered for the toughest challenges, the MS500S Lorry Truck delivers relentless performance, exceptional durability, and unstoppable torque. Powered by a 400HP Euro V Weichai engine with 1,800Nm of torque, this truck is built to conquer steep inclines and long hauls with ease. With a FAST 10-speed transmission, high-capacity aluminum fuel tank, rugged suspension system, and intelligent braking technology, it bridges power with smart engineering. The MS500S isn\'t just a truck; it\'s the driving force behind your business.',
      product_description_cn: 'Engineered for the toughest challenges, the MS500S Lorry Truck delivers relentless performance, exceptional durability, and unstoppable torque. Powered by a 400HP Euro V Weichai engine with 1,800Nm of torque, this truck is built to conquer steep inclines and long hauls with ease. With a FAST 10-speed transmission, high-capacity aluminum fuel tank, rugged suspension system, and intelligent braking technology, it bridges power with smart engineering. The MS500S isn\'t just a truck; it\'s the driving force behind your business.',
      slug_product: 'ms500s',
      created_at: '2025-06-05 14:09:02.762+07',
      created_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      updated_at: '2025-06-22 22:48:46.518+07',
      updated_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      deleted_at: null,
      deleted_by: null
    },
    {
      product_id: '71921247-cf02-478b-87d2-a541d772f22a',
      type_product_id: 'b49b58ab-d193-4de5-b383-ed78e8fb4155',
      product_name_id: 'archived-20250523112704-ms123',
      product_name_en: 'archived-20250523112704-ms123',
      product_name_cn: 'archived-20250523112704-ms123',
      banner_product: 'product/1747902612_tg-ms600-06.jpg',
      tagline_banner_product_id: 'Tough As Steel',
      tagline_banner_product_en: 'Tough As Steel',
      tagline_banner_product_cn: 'Tough As Steel',
      image_product: 'product/1747902612_slide-push-products-01.jpg',
      product_description_id: 'archived-20250523112704-lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
      product_description_en: 'archived-20250523112704-lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
      product_description_cn: 'archived-20250523112704-lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
      slug_product: 'ms123',
      created_at: '2025-05-22 15:30:12.763231+07',
      created_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      updated_at: '2025-05-22 15:30:12.761+07',
      updated_by: null,
      deleted_at: '2025-05-23 11:27:04.726+07',
      deleted_by: '73d05c65-1567-433b-83bb-4f5c4d692335'
    },
    {
      product_id: 'd764b619-ef21-44d8-ba70-387d452e7e66',
      type_product_id: '082b1a70-995d-4dc7-8092-3b3c2f496675',
      product_name_id: 'archived-2025052312028-test11',
      product_name_en: 'archived-2025052312028-test11',
      product_name_cn: 'archived-2025052312028-test11',
      banner_product: 'product/1747902696_magazine-04.jpg',
      tagline_banner_product_id: 'Tough As Steel',
      tagline_banner_product_en: 'Tough As Steel',
      tagline_banner_product_cn: 'Tough As Steel',
      image_product: 'product/1747902696_cooling-and-exhaust-systems.jpg',
      product_description_id: 'archived-2025052312028-lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
      product_description_en: 'archived-2025052312028-lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
      product_description_cn: 'archived-2025052312028-lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
      slug_product: 'test11',
      created_at: '2025-05-22 15:31:36.116775+07',
      created_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      updated_at: '2025-05-22 15:31:36.116+07',
      updated_by: null,
      deleted_at: '2025-05-23 13:20:28.735+07',
      deleted_by: '73d05c65-1567-433b-83bb-4f5c4d692335'
    },
    {
      product_id: '0f2c0c3f-7934-4872-bbbe-5bea2dce0e27',
      type_product_id: '112d78d6-c7fe-40f0-bc14-eaa6972e9e8b',
      product_name_id: 'MS700',
      product_name_en: 'MS700',
      product_name_cn: 'MS700',
      banner_product: 'product/1747974655_slide-push-products-01.jpg',
      tagline_banner_product_id: 'Delivering Efficiency',
      tagline_banner_product_en: 'Delivering Efficiency',
      tagline_banner_product_cn: 'Delivering Efficiency',
      image_product: 'product/1747974655_trucks-products-ms700-banner.png',
      product_description_id: 'Engineered to exceed expectations in the most demanding mining and hauling environments, the MS700 Series delivers uncompromising strength and efficiency. Purpose-built for high-capacity loads, this series integrates advanced performance systems with rugged durability and operator-centric comfort. Whether navigating harsh terrain or covering extended transport routes, the MS700 ensures superior operational stability, and enhanced safety—making it the trusted solution for heavy-duty industrial transport. No matter the terrain or task, our trucks are designed to excel with ease, delivering reliable performance and tailored support to ensure your operations run seamlessly in every environment.',
      product_description_en: 'Engineered to exceed expectations in the most demanding mining and hauling environments, the MS700 Series delivers uncompromising strength and efficiency. Purpose-built for high-capacity loads, this series integrates advanced performance systems with rugged durability and operator-centric comfort. Whether navigating harsh terrain or covering extended transport routes, the MS700 ensures superior operational stability, and enhanced safety—making it the trusted solution for heavy-duty industrial transport. No matter the terrain or task, our trucks are designed to excel with ease, delivering reliable performance and tailored support to ensure your operations run seamlessly in every environment.',
      product_description_cn: 'Engineered to exceed expectations in the most demanding mining and hauling environments, the MS700 Series delivers uncompromising strength and efficiency. Purpose-built for high-capacity loads, this series integrates advanced performance systems with rugged durability and operator-centric comfort. Whether navigating harsh terrain or covering extended transport routes, the MS700 ensures superior operational stability, and enhanced safety—making it the trusted solution for heavy-duty industrial transport. No matter the terrain or task, our trucks are designed to excel with ease, delivering reliable performance and tailored support to ensure your operations run seamlessly in every environment.',
      slug_product: 'ms700',
      created_at: '2025-05-23 11:30:55.883+07',
      created_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      updated_at: '2025-06-16 15:20:54.421+07',
      updated_by: 'ccdf2a53-b7b8-4d37-9d65-d30753564baa',
      deleted_at: null,
      deleted_by: null
    },
    {
      product_id: 'c10d67b8-b699-494b-88a7-81977a202625',
      type_product_id: '112d78d6-c7fe-40f0-bc14-eaa6972e9e8b',
      product_name_id: 'MS600',
      product_name_en: 'MS600',
      product_name_cn: 'MS600',
      banner_product: 'product/1750518499_banner-ms600.jpg',
      tagline_banner_product_id: 'Tough As Steel',
      tagline_banner_product_en: 'Tough As Steel',
      tagline_banner_product_cn: 'Tough As Steel',
      image_product: 'product/1747964729_trucks-products-banner.png',
      product_description_id: 'The MS600 series is built for those who demand strength and dependability in every journey. Motor Sights has earned the trust of industries that rely on consistent heavy-duty performance. Its core is engineered with advanced technology inspired by MAN, delivering a perfect balance of durability and power. Whether in off-road terrains or high-intensity applications, the MS600 doesn\'t just handle the pressure—it thrives in it. Proven in the field, this series stands as a symbol of reliability for any job, anywhere.',
      product_description_en: 'The MS600 series is built for those who demand strength and dependability in every journey. Motor Sights has earned the trust of industries that rely on consistent heavy-duty performance. Its core is engineered with advanced technology inspired by MAN, delivering a perfect balance of durability and power. Whether in off-road terrains or high-intensity applications, the MS600 doesn\'t just handle the pressure—it thrives in it. Proven in the field, this series stands as a symbol of reliability for any job, anywhere.',
      product_description_cn: 'The MS600 series is built for those who demand strength and dependability in every journey. Motor Sights has earned the trust of industries that rely on consistent heavy-duty performance. Its core is engineered with advanced technology inspired by MAN, delivering a perfect balance of durability and power. Whether in off-road terrains or high-intensity applications, the MS600 doesn\'t just handle the pressure—it thrives in it. Proven in the field, this series stands as a symbol of reliability for any job, anywhere.',
      slug_product: 'ms600',
      created_at: '2025-05-21 09:44:52.166+07',
      created_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      updated_at: '2025-06-21 22:08:19.111+07',
      updated_by: 'ccdf2a53-b7b8-4d37-9d65-d30753564baa',
      deleted_at: null,
      deleted_by: null
    },
    {
      product_id: '00409de1-5f5e-4b26-83c5-f549b9f03077',
      type_product_id: 'b49b58ab-d193-4de5-b383-ed78e8fb4155',
      product_name_id: 'MS500S',
      product_name_en: 'MS500S',
      product_name_cn: 'MS500S',
      banner_product: 'product/1750524542_MS500S-TH.jpg',
      tagline_banner_product_id: 'Power That Moves Business',
      tagline_banner_product_en: 'Power That Moves Business',
      tagline_banner_product_cn: 'Power That Moves Business',
      image_product: 'product/1750607258_MS500S-TH-PNG.png',
      product_description_id: 'The MS500S Tractor Head is a powerful fusion of advanced engineering, proven reliability, and business-ready performance. Powered by a 400HP Weichai Euro V engine and delivering 1800Nm of torque, it\'s equipped with a durable FAST transmission system built to tackle even the heaviest loads with ease, no matter the terrain or challenge. Engineered for logistics, construction, and industrial operations, the MS500S ensures maximum uptime, long-distance durability, and cost-efficient operation. Drive with confidence. Operate with power. Lead with performance.',
      product_description_en: 'The MS500S Tractor Head is a powerful fusion of advanced engineering, proven reliability, and business-ready performance. Powered by a 400HP Weichai Euro V engine and delivering 1800Nm of torque, it\'s equipped with a durable FAST transmission system built to tackle even the heaviest loads with ease, no matter the terrain or challenge. Engineered for logistics, construction, and industrial operations, the MS500S ensures maximum uptime, long-distance durability, and cost-efficient operation. Drive with confidence. Operate with power. Lead with performance.',
      product_description_cn: 'The MS500S Tractor Head is a powerful fusion of advanced engineering, proven reliability, and business-ready performance. Powered by a 400HP Weichai Euro V engine and delivering 1800Nm of torque, it\'s equipped with a durable FAST transmission system built to tackle even the heaviest loads with ease, no matter the terrain or challenge. Engineered for logistics, construction, and industrial operations, the MS500S ensures maximum uptime, long-distance durability, and cost-efficient operation. Drive with confidence. Operate with power. Lead with performance.',
      slug_product: 'ms500s',
      created_at: '2025-06-05 14:08:22.153+07',
      created_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      updated_at: '2025-06-22 22:47:38.972+07',
      updated_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      deleted_at: null,
      deleted_by: null
    },
    {
      product_id: '65b6c1ea-f92b-4106-91d1-7b4116355fb5',
      type_product_id: '082b1a70-995d-4dc7-8092-3b3c2f496675',
      product_name_id: 'MS500',
      product_name_en: 'MS500',
      product_name_cn: 'MS500',
      banner_product: 'product/1750524091_banner.jpg',
      tagline_banner_product_id: 'Engineered to Carry More',
      tagline_banner_product_en: 'Engineered to Carry More',
      tagline_banner_product_cn: 'Engineered to Carry More',
      image_product: 'product/1750606859_MS500-Lorry.png',
      product_description_id: 'When performance meets precision, you get the MS500 Lorry Truck, a dependable powerhouse built to move cargo efficiently, safely, and consistently. With a 300HP Cummins engine and 1,100Nm of torque, it delivers the strength needed to handle heavy loads with ease. Paired with a FAST 8-speed transmission, ensuring smooth handling under pressure. Its aerodynamic design, aluminum alloy fuel tank, and Euro V compliance make it both tough and environmentally responsible. The MS500 is optimized to carry more, built to go further.',
      product_description_en: 'When performance meets precision, you get the MS500 Lorry Truck, a dependable powerhouse built to move cargo efficiently, safely, and consistently. With a 300HP Cummins engine and 1,100Nm of torque, it delivers the strength needed to handle heavy loads with ease. Paired with a FAST 8-speed transmission, ensuring smooth handling under pressure. Its aerodynamic design, aluminum alloy fuel tank, and Euro V compliance make it both tough and environmentally responsible. The MS500 is optimized to carry more, built to go further.',
      product_description_cn: 'When performance meets precision, you get the MS500 Lorry Truck, a dependable powerhouse built to move cargo efficiently, safely, and consistently. With a 300HP Cummins engine and 1,100Nm of torque, it delivers the strength needed to handle heavy loads with ease. Paired with a FAST 8-speed transmission, ensuring smooth handling under pressure. Its aerodynamic design, aluminum alloy fuel tank, and Euro V compliance make it both tough and environmentally responsible. The MS500 is optimized to carry more, built to go further.',
      slug_product: 'ms500',
      created_at: '2025-06-05 14:04:58.963+07',
      created_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      updated_at: '2025-06-22 22:40:59.454+07',
      updated_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      deleted_at: null,
      deleted_by: null
    },
    {
      product_id: 'e5effe32-5f28-4040-aa65-98492e89cde9',
      type_product_id: 'b49b58ab-d193-4de5-b383-ed78e8fb4155',
      product_name_id: 'MS500',
      product_name_en: 'MS500',
      product_name_cn: 'MS500',
      banner_product: 'product/1750524530_MS500-TH.jpg',
      tagline_banner_product_id: 'Efficient Power. Everyday Performance',
      tagline_banner_product_en: 'Efficient Power. Everyday Performance',
      tagline_banner_product_cn: 'Efficient Power. Everyday Performance',
      image_product: 'product/1750607073_MS500-TH.png',
      product_description_id: 'The MS500 Tractor Head is driven by a dependable 300HP Cummins Euro V engine, that offers an ideal mix of strength, fuel economy, and environmental care. The lightweight frame supports greater payloads, making it a smart choice for regional and city-to-city transport. Paired with 1100Nm of torque and a seamless FAST 8-speed transmission, it\'s built to deliver steady performance in busy roads and time-sensitive operations, combining safety with efficiency on every journey.',
      product_description_en: 'The MS500 Tractor Head is driven by a dependable 300HP Cummins Euro V engine, that offers an ideal mix of strength, fuel economy, and environmental care. The lightweight frame supports greater payloads, making it a smart choice for regional and city-to-city transport. Paired with 1100Nm of torque and a seamless FAST 8-speed transmission, it\'s built to deliver steady performance in busy roads and time-sensitive operations, combining safety with efficiency on every journey.',
      product_description_cn: 'The MS500 Tractor Head is driven by a dependable 300HP Cummins Euro V engine, that offers an ideal mix of strength, fuel economy, and environmental care. The lightweight frame supports greater payloads, making it a smart choice for regional and city-to-city transport. Paired with 1100Nm of torque and a seamless FAST 8-speed transmission, it\'s built to deliver steady performance in busy roads and time-sensitive operations, combining safety with efficiency on every journey.',
      slug_product: 'ms500',
      created_at: '2025-06-05 14:06:41.54+07',
      created_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      updated_at: '2025-06-22 22:44:33.898+07',
      updated_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      deleted_at: null,
      deleted_by: null
    },
    {
      product_id: '7581e4eb-befa-40d7-955e-2ca6ebceaae6',
      type_product_id: '112d78d6-c7fe-40f0-bc14-eaa6972e9e8b',
      product_name_id: 'MS500S',
      product_name_en: 'MS500S',
      product_name_cn: 'MS500S',
      banner_product: 'product/1750523355_MS500S-DT.jpg',
      tagline_banner_product_id: 'All Muscle. No Excuses',
      tagline_banner_product_en: 'All Muscle. No Excuses',
      tagline_banner_product_cn: 'All Muscle. No Excuses',
      image_product: 'product/1750607369_MS500S-DT-PNG.png',
      product_description_id: 'The MS 5005 Dump Truck is crafted for durability, dependability, and high-impact performance. Fueled by a robust 400HP WEICHAI Euro V engine and delivering 1,800Nm of torque, it comes equipped with a resilient 10-speed FAST transmission, heavy-duty double-stage axles, and an intelligent retarder braking system offering superior handling, safety, and efficiency. The MS500S goes beyond expectations, a reliable powerhouse designed to haul heavier loads, master challenging terrain, and withstand the toughest conditions.',
      product_description_en: 'The MS 5005 Dump Truck is crafted for durability, dependability, and high-impact performance. Fueled by a robust 400HP WEICHAI Euro V engine and delivering 1,800Nm of torque, it comes equipped with a resilient 10-speed FAST transmission, heavy-duty double-stage axles, and an intelligent retarder braking system offering superior handling, safety, and efficiency. The MS500S goes beyond expectations, a reliable powerhouse designed to haul heavier loads, master challenging terrain, and withstand the toughest conditions.',
      product_description_cn: 'The MS 5005 Dump Truck is crafted for durability, dependability, and high-impact performance. Fueled by a robust 400HP WEICHAI Euro V engine and delivering 1,800Nm of torque, it comes equipped with a resilient 10-speed FAST transmission, heavy-duty double-stage axles, and an intelligent retarder braking system offering superior handling, safety, and efficiency. The MS500S goes beyond expectations, a reliable powerhouse designed to haul heavier loads, master challenging terrain, and withstand the toughest conditions.',
      slug_product: 'ms500s',
      created_at: '2025-06-20 13:58:40.499+07',
      created_by: 'ccdf2a53-b7b8-4d37-9d65-d30753564baa',
      updated_at: '2025-06-22 22:49:29.562+07',
      updated_by: '73d05c65-1567-433b-83bb-4f5c4d692335',
      deleted_at: null,
      deleted_by: null
    }
  ]);
};

